title: "[Idea] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What's the idea?
      description: Describe the feature or improvement you'd like to see.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would you use this?
