#!/usr/bin/env node
// Wraps the built IIFE bundle in a plain ES module that default-exports its
// source as a string. The worker imports that module to serve /tracker.js,
// so the script travels through wrangler's bundler as ordinary code and
// needs no `[[rules]] type = "Text"` entry in wrangler.toml. Without this
// wrapper a config that lacked the rule would bundle the browser script as
// a module and crash the worker at startup on `document`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dist = resolve(__dirname, '../dist');
const source = readFileSync(resolve(dist, 'tracker.iife.js'), 'utf-8');

writeFileSync(
  resolve(dist, 'tracker-script.mjs'),
  `// Generated by scripts/emit-module.mjs from tracker.iife.js. Do not edit.\nexport default ${JSON.stringify(source)};\n`,
);
writeFileSync(
  resolve(dist, 'tracker-script.d.mts'),
  `declare const source: string;\nexport default source;\n`,
);
console.log('[emit-module] wrote dist/tracker-script.mjs');
